# File generated by CompCert 2.4
# Command line: -fno-peeps -stdlib ../../runtime -dc -dclight -dasm -S -o add_vec.handtuned.s add_vec.c
	.section	.rodata
	.align	1
__stringlit_1:
	.ascii	"total summed up to: %f\012\000"
	.type	__stringlit_1, @object
	.size	__stringlit_1, . - __stringlit_1
	.section	.rodata
	.align	4
	.global	A
A:
	.long	-966564955
	.long	-126059388
	.long	-294160487
	.long	-159679603
	.long	-855539
	.long	-697603139
	.long	-563122255
	.long	-1849309868
	.long	1613770832
	.long	33620227
	.long	-832084055
	.long	1445669757
	.long	-402719207
	.long	-1244145822
	.long	1303096294
	.long	-327780710
	.long	-1882535355
	.long	528646813
	.long	-1983264448
	.long	-92439161
	.long	-268764651
	.long	-1302767125
	.long	-1907931191
	.long	-68095989
	.long	1101901292
	.long	-1277897625
	.long	1604494077
	.long	1169141738
	.long	597466303
	.long	1403299063
	.long	-462261610
	.long	-1681866661
	.long	1974974402
	.long	-503448292
	.long	1033081774
	.long	1277568618
	.long	1815492186
	.long	2118074177
	.long	-168298750
	.long	-2083730353
	.long	1748251740
	.long	1369810420
	.long	-773462732
	.long	-101584632
	.long	-495881837
	.long	-1411852173
	.long	1647391059
	.long	706024767
	.long	134480908
	.long	-1782069422
	.long	1176707941
	.long	-1648114850
	.long	806885416
	.long	932615841
	.long	168101135
	.long	798661301
	.long	235341577
	.long	605164086
	.long	461406363
	.long	-538779075
	.long	-840176858
	.long	1311188841
	.long	2142417613
	.long	-361400929
	.long	302582043
	.long	495158174
	.long	1479289972
	.long	874125870
	.long	907746093
	.long	-596742478
	.long	-1269146898
	.long	1537253627
	.long	-1538108682
	.long	1983593293
	.long	-1210657183
	.long	2108928974
	.long	1378429307
	.long	-572267714
	.long	1580150641
	.long	327451799
	.long	-1504488459
	.long	-1177431704
	.long	0
	.long	-1041371860
	.long	1075847264
	.long	-469959649
	.long	2041688520
	.long	-1235526675
	.long	-731223362
	.long	-1916023994
	.long	1740553945
	.long	1916352843
	.long	-1807070498
	.long	-1739830060
	.long	-1336387352
	.long	-2049978550
	.long	-1143943061
	.long	-974131414
	.long	1336584933
	.long	-302253290
	.long	-2042412091
	.long	-1706209833
	.long	1714631509
	.long	293963156
	.long	-1975171633
	.long	-369493744
	.long	67240454
	.long	-25198719
	.long	-1605349136
	.long	2017213508
	.long	631218106
	.long	1269344483
	.long	-1571728909
	.long	1571005438
	.long	-2143272768
	.long	93294474
	.long	1066570413
	.long	563977660
	.long	1882732616
	.long	-235539196
	.long	1673313503
	.long	2008463041
	.long	-1344611723
	.long	1109467491
	.long	537923632
	.long	-436207846
	.long	-34344178
	.long	-1076702611
	.long	-2117218996
	.long	403442708
	.long	638784309
	.long	-1007883217
	.long	-1101045791
	.long	899127202
	.long	-2008791860
	.long	773265209
	.long	-1815821225
	.long	1437050866
	.long	-58818942
	.long	2050833735
	.long	-932944724
	.long	-1168286233
	.long	840505643
	.long	-428641387
	.long	-1067425632
	.long	427917720
	.long	-1638969391
	.long	-1545806721
	.long	1143087718
	.long	1412049534
	.long	999329963
	.long	193497219
	.long	-1941551414
	.long	-940642775
	.long	1807268051
	.long	672404540
	.long	-1478566279
	.long	-1134666014
	.long	369822493
	.long	-1378100362
	.long	-606019525
	.long	1681011286
	.long	1949973070
	.long	336202270
	.long	-1840690725
	.long	201721354
	.long	1210328172
	.long	-1201906460
	.long	-1614626211
	.long	-1110191250
	.long	1135389935
	.long	-1000185178
	.long	965841320
	.long	831886756
	.long	-739974089
	.long	-226920053
	.long	-706222286
	.long	-1949775805
	.long	1849112409
	.long	-630362697
	.long	26054028
	.long	-1311386268
	.long	-1672589614
	.long	1235855840
	.long	-663982924
	.long	-1403627782
	.long	-202050553
	.long	-806688219
	.long	-899324497
	.long	-193299826
	.long	1202630377
	.long	268961816
	.long	1874508501
	.long	-260540280
	.long	1243948399
	.long	1546530418
	.long	941366308
	.long	1470539505
	.long	1941222599
	.long	-1748580783
	.long	-873928669
	.long	-1579295364
	.long	-395021156
	.long	1042226977
	.long	-1773450275
	.long	1639824860
	.long	227249030
	.long	260737669
	.long	-529502064
	.long	2084453954
	.long	1907733956
	.long	-865704278
	.long	-1874310952
	.long	100860677
	.long	-134810111
	.long	470683154
	.long	-1033805405
	.long	1781871967
	.long	-1370007559
	.long	1773779408
	.long	394692241
	.long	-1715355304
	.long	974986535
	.long	664706745
	.long	-639508168
	.long	-336005101
	.long	731420851
	.long	571543859
	.long	-764843589
	.long	-1445340816
	.long	126783113
	.long	865375399
	.long	765172662
	.long	1008606754
	.long	361203602
	.long	-907417312
	.long	-2016489911
	.long	-1437248001
	.long	1344809080
	.long	-1512054918
	.long	59542671
	.long	1503764984
	.long	160008576
	.long	437062935
	.long	1707065306
	.long	-672733647
	.long	-2076032314
	.long	-798463816
	.long	-2109652541
	.long	697932208
	.long	1512910199
	.long	504303377
	.long	2075177163
	.long	-1470868228
	.long	1841019862
	.long	739644986
	.type	A, @object
	.size	A, . - A
	.section	.rodata
	.align	4
	.global	B
B:
	.long	-1513725085
	.long	-2064089988
	.long	-1712425097
	.long	-1913226373
	.long	234877682
	.long	-1110021269
	.long	-1310822545
	.long	1418839493
	.long	1348481072
	.long	50462977
	.long	-1446090905
	.long	2102799147
	.long	434634494
	.long	1656084439
	.long	-431117397
	.long	-1695779210
	.long	1167051466
	.long	-1658879358
	.long	1082771913
	.long	-2013627011
	.long	368048890
	.long	-340633255
	.long	-913422521
	.long	201060592
	.long	-331240019
	.long	1739838676
	.long	-44064094
	.long	-364531793
	.long	-1088185188
	.long	-145513308
	.long	-1763413390
	.long	1536934080
	.long	-1032472649
	.long	484572669
	.long	-1371696237
	.long	1783375398
	.long	1517041206
	.long	1098792767
	.long	49674231
	.long	1334037708
	.long	1550332980
	.long	-195975771
	.long	886171109
	.long	150598129
	.long	-1813876367
	.long	1940642008
	.long	1398944049
	.long	1059722517
	.long	201851908
	.long	1385547719
	.long	1699095331
	.long	1587397571
	.long	674240536
	.long	-1590192490
	.long	252314885
	.long	-1255171430
	.long	151914247
	.long	908333586
	.long	-1692696448
	.long	1038082786
	.long	651029483
	.long	1766729511
	.long	-847269198
	.long	-1612024459
	.long	454166793
	.long	-1642232957
	.long	1951935532
	.long	775166490
	.long	758520603
	.long	-1294176658
	.long	-290170278
	.long	-77881184
	.long	-157003182
	.long	1299594043
	.long	1639438038
	.long	-830622797
	.long	2068982057
	.long	1054729187
	.long	1901997871
	.long	-1760328572
	.long	-173649069
	.long	1757008337
	.long	0
	.long	750906861
	.long	1614815264
	.long	535035132
	.long	-931548751
	.long	-306816165
	.long	-1093375382
	.long	1183697867
	.long	-647512386
	.long	1265776953
	.long	-560706998
	.long	-728216500
	.long	-391096232
	.long	1250283471
	.long	1807470800
	.long	717615087
	.long	-447763798
	.long	384695291
	.long	-981056701
	.long	-677753523
	.long	1432761139
	.long	-1810791035
	.long	-813021883
	.long	283769337
	.long	100925954
	.long	-2114027649
	.long	-257929136
	.long	1148730428
	.long	-1171939425
	.long	-481580888
	.long	-207466159
	.long	-27417693
	.long	-1065336768
	.long	-1979347057
	.long	-1388342638
	.long	-1138647651
	.long	1215313976
	.long	82966005
	.long	-547111748
	.long	-1049119050
	.long	1974459098
	.long	1665278241
	.long	807407632
	.long	451280895
	.long	251524083
	.long	1841287890
	.long	1283575245
	.long	337120268
	.long	891687699
	.long	801369324
	.long	-507617441
	.long	-1573546089
	.long	-863484860
	.long	959321879
	.long	1469301956
	.long	-229267545
	.long	-2097381762
	.long	1199193405
	.long	-1396153244
	.long	-407216803
	.long	724703513
	.long	-1780059277
	.long	-1598005152
	.long	-1743158911
	.long	-778154161
	.long	2141445340
	.long	1715741218
	.long	2119445034
	.long	-1422159728
	.long	-2096396152
	.long	-896776634
	.long	700968686
	.long	-747915080
	.long	1009259540
	.long	2041044702
	.long	-490971554
	.long	487983883
	.long	1991105499
	.long	1004265696
	.long	1449407026
	.long	1316239930
	.long	504629770
	.long	-611169975
	.long	168560134
	.long	1816667172
	.long	-457679780
	.long	1570751170
	.long	1857934291
	.long	-280777556
	.long	-1497079198
	.long	-1472622191
	.long	-1540254315
	.long	936633572
	.long	-1947043463
	.long	852879335
	.long	1133234376
	.long	1500395319
	.long	-1210421907
	.long	-1946055283
	.long	1689376213
	.long	-761508274
	.long	-532043351
	.long	-1260884884
	.long	-89369002
	.long	133428468
	.long	634383082
	.long	-1345690267
	.long	-1896580486
	.long	-381178194
	.long	403703816
	.long	-714097990
	.long	-1997506440
	.long	1867130149
	.long	1918643758
	.long	607656988
	.long	-245913946
	.long	-948718412
	.long	1368901318
	.long	600565992
	.long	2090982877
	.long	-1662487436
	.long	557719327
	.long	-577352885
	.long	-597574211
	.long	-2045932661
	.long	-2062579062
	.long	-1864339344
	.long	1115438654
	.long	-999180875
	.long	-1429445018
	.long	-661632952
	.long	84280067
	.long	33027830
	.long	303828494
	.long	-1547542175
	.long	1600795957
	.long	-106014889
	.long	-798377543
	.long	-1860729210
	.long	1486471617
	.long	658119965
	.long	-1188585826
	.long	953803233
	.long	334231800
	.long	-1288988520
	.long	857870609
	.long	-1143838359
	.long	1890179545
	.long	-1995993458
	.long	-1489791852
	.long	-1238525029
	.long	574365214
	.long	-1844082809
	.long	550103529
	.long	1233637070
	.long	-5614251
	.long	2018519080
	.long	2057691103
	.long	-1895592820
	.long	-128343647
	.long	-2146858615
	.long	387583245
	.long	-630865985
	.long	836232934
	.long	-964410814
	.long	-1194301336
	.long	-1014873791
	.long	-1339450983
	.long	2002398509
	.long	287182607
	.long	-881086288
	.long	-56077228
	.long	-697451589
	.long	975967766
	.type	B, @object
	.size	B, . - B
	.text
	.align	16
	.globl sum
sum:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %edx
	movl	%edx, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%esi, 8(%esp)
	movl	%edi, 12(%esp)
	movl	%ebp, 16(%esp)
	movl	0(%edx), %ebp
	movl	4(%edx), %edi
	movl	8(%edx), %esi
	movl	12(%edx), %ebx
	movl	16(%edx), %eax
	testl	%eax, %eax
	jl	.L100
	xorl	%eax, %eax
.L101:
	leal	-3(%ebx), %ecx
	cmpl	%ecx, %eax
	jge	.L102
	movsd	0(%ebp,%eax,8), %xmm4
	movsd	0(%edi,%eax,8), %xmm0
	mulsd	%xmm0, %xmm4
	movsd	8(%ebp,%eax,8), %xmm1
	movsd	8(%edi,%eax,8), %xmm6
	mulsd	%xmm6, %xmm1
	movsd	16(%ebp,%eax,8), %xmm3
	movsd	16(%edi,%eax,8), %xmm7
	mulsd	%xmm7, %xmm3
	movsd	24(%ebp,%eax,8), %xmm2
	movsd	24(%edi,%eax,8), %xmm5
	mulsd	%xmm5, %xmm2
	movsd	%xmm4, 0(%esi,%eax,8)
	movsd	%xmm1, 8(%esi,%eax,8)
	movsd	%xmm3, 16(%esi,%eax,8)
	movsd	%xmm2, 24(%esi,%eax,8)
	leal	4(%eax), %eax
	jmp	.L101
.L102:
	cmpl	%ebx, %eax
	jge	.L100
	movsd	0(%ebp,%eax,8), %xmm0
	movsd	0(%edi,%eax,8), %xmm2
	mulsd	%xmm2, %xmm0
	movsd	%xmm0, 0(%esi,%eax,8)
	leal	1(%eax), %eax
	jmp	.L102
.L100:
	movl	4(%esp), %ebx
	movl	8(%esp), %esi
	movl	12(%esp), %edi
	movl	16(%esp), %ebp
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	sum, @function
	.size	sum, . - sum
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subl	$36, %esp
	.cfi_adjust_cfa_offset	36
	leal	40(%esp), %edx
	movl	%edx, 20(%esp)
	movl	%ebx, 24(%esp)
	movl	%esi, 28(%esp)
	movl	$1024, %edx
	movl	%edx, 0(%esp)
	call	malloc
	movl	%eax, %ebx
	xorl	%esi, %esi
.L103:
	leal	A, %edx
	leal	B, %ecx
	movl	$128, %eax
	movl	%edx, 0(%esp)
	movl	%ecx, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	%eax, 12(%esp)
	movl	%esi, 16(%esp)
	call	sum
	leal	1(%esi), %esi
	cmpl	$40000000, %esi
	jl	.L103
	leal	__stringlit_1, %edx
	movsd	800(%ebx), %xmm1
	movl	%edx, 0(%esp)
	movsd	%xmm1, 4(%esp)
	call	printf
	xorl	%eax, %eax
	movl	24(%esp), %ebx
	movl	28(%esp), %esi
	addl	$36, %esp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
