# File generated by CompCert 2.4
# Command line: -fno-peeps -stdlib ../../runtime -dc -dclight -dasm -S -o fib.handtuned.s fib.c
	.section	.rodata
	.align	1
__stringlit_1:
	.ascii	"fib(%d) = %d\012\000"
	.type	__stringlit_1, @object
	.size	__stringlit_1, . - __stringlit_1
	.text
	.align	16
	.globl fib
fib:
	.cfi_startproc
	subl	$20, %esp
	.cfi_adjust_cfa_offset	20
	leal	24(%esp), %edx
	movl	%edx, 4(%esp)
	movl	%ebx, 8(%esp)
	movl	%esi, 12(%esp)
	movl	0(%edx), %esi
	cmpl	$2, %esi
	jl	.L100
	leal	-1(%esi), %eax
	movl	%eax, 0(%esp)
	call	fib
	movl	%eax, %ebx
	leal	-2(%esi), %ecx
	movl	%ecx, 0(%esp)
	call	fib
	leal	0(%ebx,%eax,1), %eax
	jmp	.L101
.L100:
	movl	$1, %eax
.L101:
	movl	8(%esp), %ebx
	movl	12(%esp), %esi
	addl	$20, %esp
	ret
	.cfi_endproc
	.type	fib, @function
	.size	fib, . - fib
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subl	$28, %esp
	.cfi_adjust_cfa_offset	28
	leal	32(%esp), %edx
	movl	%edx, 12(%esp)
	movl	%ebx, 16(%esp)
	movl	0(%edx), %ecx
	movl	4(%edx), %ebx
	cmpl	$2, %ecx
	jl	.L102
	movl	4(%ebx), %ecx
	movl	%ecx, 0(%esp)
	call	atoi
	movl	%eax, %ebx
	jmp	.L103
.L102:
	movl	$43, %ebx
.L103:
	movl	%ebx, 0(%esp)
	call	fib
	leal	__stringlit_1, %ecx
	movl	%ecx, 0(%esp)
	movl	%ebx, 4(%esp)
	movl	%eax, 8(%esp)
	call	printf
	xorl	%eax, %eax
	movl	16(%esp), %ebx
	addl	$28, %esp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
